enh10

diff --git a/zeppelin-ci/build/ciyaml b/zeppelin-ci/build/ciyaml
--- a/zeppelin-ci/build/ciyaml
+++ b/zeppelin-ci/build/ciyaml
@@ -161,6 +161,12 @@ function parse_etc
 	echo "set -e" >> ${base_path}/script.sh
 	cat $yaml_file | $EXE get-values script >> ${base_path}/script.sh
 	chmod +x ${base_path}/script.sh
+
+	# failure
+	echo "#!/bin/bash" > ${base_path}/failure.sh
+	echo "set -e" >> ${base_path}/failure.sh
+	cat $yaml_file | $EXE get-values failure >> ${base_path}/failure.sh
+	chmod +x ${base_path}/failure.sh
 }
 
 
